name: CI

on: pull_request

jobs:
  compile-and-test:
    name: Compile and test
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Build image and run tests
        uses: docker/build-push-action@v4
        with:
          context: ./test/Dockerfile
          tags: razor-tests
          push: false
