name: Release

on:
  push:
    branches:
      - master

jobs:
  compile-and-release:
    name: Compile and release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build image
        run: ./docker/build.sh

      - name: Upload Razor (RockyLinux8) to releases
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./docker/pkgs/razor-rockylinux8
          asset_name: razor-rockylinux8
          tag: ${{ github.ref }}
          overwrite: false
          body: "This is the automatic release done by Github actions with every new push to the master branch."
